files:
- Frame2FEM.tcl
id: quo-08
synopsis: In this example, Bayesian estimation is used to estimate column stiffnesses
  of a simple steel frame, given data about it's mode shapes and mass distribution.
title: Bayesian Calibration - Steel Frame
