files:
- Rosen.py
- RosenParams.py
id: quo-06
synopsis: In this example, a **parameter estimation** routine is used to solve a classical
  optimization problem for which an analytic solution is known.
title: Optimization
