files:
- Frame2FEM.tcl
id: quo-07
synopsis: In this example, a parameter estimation routine is used to estimate column
  stiffnesses of a simple steel frame, given data about it's mode shapes and mass
  distribution.
title: Conventional Calibration - Steel Frame
