files:
- Rosen.py
- RosenParams.py
id: quo-05
synopsis: This example illustrates how Python scripting can be used with quoFEM to
  express general mathematical models without the use of a dedicated finite element
  analysis engine.
title: Basic modeling with Python
