files:
- TrussModel.tcl
- TrussPost.tcl
id: quo-01
synopsis: This example uses quoFEM to estimate the first and second central moments
  of a FE model's response, given the marginal distributions of various random parameters.
title: Forward Propagation - OpenSees/Tcl
